# install.packages("reticulate")
## join_data_2 결측값 처리
### 띄어쓰기 안된 데이터 띄어쓰기 하기
library(reticulate)
install_miniconda()
remotes::install_github("haven-jeon/KoSpacing",force = TRUE)
library(KoSpacing)


# 맨 처음에만 set_env()할것
#set_env()
address_list <- c()
for(i in c(1:length(duplicated_data$X.1))){
  address_list <- c(address_list,spacing(duplicated_data$X.1[i]))
}
address_list
address_list[36] <- "세종특별자치시 고운동"
address_list[37] <- "세종특별자치시 금남면"
address_list[38] <- "세종특별자치시 나성동"
address_list[39] <- "세종특별자치시 다정동"
address_list[40] <- "세종특별자치시 대평동"
address_list[41] <- "세종특별자치시 도담동"
address_list[42] <- "세종특별자치시 반곡동"
address_list[43] <- "세종특별자치시 보람동"
address_list[44] <- "세종특별자치시 부강면"
address_list[45] <- "세종특별자치시 산울동"
address_list[46] <- "세종특별자치시 새롬동"
address_list[47] <- "세종특별자치시 소담동"
address_list[48] <- "세종특별자치시 소정면"
address_list[49] <- "세종특별자치시 아름동"
address_list[50] <- "세종특별자치시 어진동"
address_list[51] <- "세종특별자치시 연기면"
address_list[52] <- "세종특별자치시 연동면"
address_list[53] <- "세종특별자치시 연서면"
address_list[54] <- "세종특별자치시 장군면"
address_list[55] <- "세종특별자치시 전동면"
address_list[56] <- "세종특별자치시 전의면"
address_list[57] <- "세종특별자치시 조치원읍"
address_list[58] <- "세종특별자치시 종촌동"
address_list[59] <- "세종특별자치시 집현동"
address_list[60] <- "세종특별자치시 한솔동"
address_list[61] <- "세종특별자치시 합강동"
address_list[62] <- "세종특별자치시 해밀동"
address_list[63] <- "경기도 수원시 권선구 곡반정동"
address_list[79] <- "경기도 수원시 영통구 매탄동"
address_list[89] <- "경기도 수원시 장안구 율전동"
address_list[105] <- "경기도 수원시 팔달구 매향동"
address_list[110] <- "경기도 수원시 팔달구 인계동"
address_list[136] <- "경기도 성남시 수정구 단대동"
address_list[141] <- "경기도 성남시 수정구 상적동"
address_list[159] <- "경기도 성남시 중원구 하대원동"
address_list[163] <- "경기도 안양시 만안구 박달동"
address_list[164] <- "경기도 안양시 만안구 석수동"
address_list[165] <- "경기도 안양시 만안구 안양동"
address_list[169] <- "경기도 안산시 단원구 대부동동"
address_list[176] <- "경기도 안산시 단원구 와동"
address_list[182] <- "경기도 안산시 상록구 건건동"
address_list[186] <- "경기도 안산시 상록구 사사동"
address_list[187] <- "경기도 안산시 상록구 성포동"
address_list[193] <- "경기도 안산시 상록구 장상동"
address_list[194] <- "경기도 안산시 상록구 장하동"
address_list[200] <- "경기도 고양시 덕양구 내유동"
address_list[204] <- "경기도 고양시 덕양구 도내동"
address_list[210] <- "경기도 고양시 덕양구 성사동"
address_list[221] <- "경기도 고양시 덕양구 행주내동"
address_list[222] <- "경기도 고양시 덕양구 행주외동"
address_list[223] <- "경기도 고양시 덕양구 향동동"
address_list[234] <- "경기도 고양시 일산동구 성석동"
address_list[257] <- "경기도 용인시 기흥구 상갈동"
address_list[265] <- "경기도 용인시 기흥구 청덕동"
address_list[270] <- "경기도 용인시 수지구 성복동"
address_list[283] <- "경기도 용인시 처인구 역북동"
address_list[290] <- "경기도 용인시 처인구 호동"
address_list[292] <- "경기도 파주시 당하동"
address_list[314] <- "충청북도 청주시 상당구 남문로1가"
address_list[315] <- "충청북도 청주시 상당구 남문로2가"
address_list[351] <- "충청북도 청주시 서원구 성화동"
address_list[373] <- "충청북도 청주시 흥덕구 가경동"
address_list[429] <- "충청북도 충주시 용탄동"
address_list[434] <- "충청남도 천안시 동남구 동면"
address_list[436] <- "충청남도 천안시 동남구 문화동"
address_list[454] <- "충청남도 천안시 동남구 청당동"
address_list[455] <- "충청남도 천안시 동남구 청수동"
address_list[468] <- "충청남도 천안시 서북구 와촌동"
address_list[476] <- "전라북도 전주시 덕진구 덕진동1가"
address_list[477] <- "전라북도 전주시 덕진구 덕진동2가"
address_list[484] <- "전라북도 전주시 덕진구 송천동1가"
address_list[485] <- "전라북도 전주시 덕진구 송천동2가"
address_list[487] <- "전라북도 전주시 덕진구 여의동2가"
address_list[496] <- "전라북도 전주시 덕진구 전미동1가"
address_list[497] <- "전라북도 전주시 덕진구 전미동2가"
address_list[500] <- "전라북도 전주시 덕진구 팔복동1가"
address_list[501] <- "전라북도 전주시 덕진구 팔복동2가"
address_list[502] <- "전라북도 전주시 덕진구 팔복동3가"
address_list[503] <- "전라북도 전주시 덕진구 팔복동4가"
address_list[504] <- "전라북도 전주시 덕진구 호성동1가"
address_list[506] <- "전라북도 전주시 덕진구 호성동3가"
address_list[508] <- "전라북도 전주시 완산구 경원동1가"
address_list[509] <- "전라북도 전주시 완산구 경원동2가"
address_list[510] <- "전라북도 전주시 완산구 경원동3가"
address_list[521] <- "전라북도 전주시 완산구 삼천동1가"
address_list[522] <- "전라북도 전주시 완산구 삼천동2가"
address_list[529] <- "전라북도 전주시 완산구 서완산동1가"
address_list[536] <- "전라북도 전주시 완산구 중노송동"
address_list[537] <- "전라북도 전주시 완산구 중앙동1가"
address_list[538] <- "전라북도 전주시 완산구 중앙동2가"
address_list[539] <- "전라북도 전주시 완산구 중앙동3가"
address_list[540] <- "전라북도 전주시 완산구 중앙동4가"
address_list[541] <- "전라북도 전주시 완산구 중인동"
address_list[542] <- "전라북도 전주시 완산구 중화산동1가"
address_list[543] <- "전라북도 전주시 완산구 중화산동2가"
address_list[548] <- "전라북도 전주시 완산구 풍남동1가"
address_list[550] <- "전라북도 전주시 완산구 풍남동3가"
address_list[553] <- "전라북도 전주시 완산구 효자동3가"
address_list[555] <- "경상북도 포항시 남구 대도동"
address_list[556] <- "경상북도 포항시 남구 대송면"
address_list[567] <- "경상북도 포항시 남구 인덕동"
address_list[572] <- "경상북도 포항시 남구 청림동"
address_list[601] <- "경상북도 포항시 북구 청하면"
address_list[604] <- "경상북도 포항시 북구 항구동"
address_list[614] <- "경상남도 창원시 마산합포구 대성동1가"
address_list[633] <- "경상남도 창원시 마산합포구 신포동1가"
address_list[634] <- "경상남도 창원시 마산합포구 신포동2가"
address_list[648] <- "경상남도 창원시 마산합포구 자산동"
address_list[649] <- "경상남도 창원시 마산합포구 장군동1가"
address_list[650] <- "경상남도 창원시 마산합포구 장군동2가"
address_list[651] <- "경상남도 창원시 마산합포구 장군동3가"
address_list[654] <- "경상남도 창원시 마산합포구 중성동"
address_list[655] <- "경상남도 창원시 마산합포구 중앙동1가"
address_list[656] <- "경상남도 창원시 마산합포구 중앙동2가"
address_list[657] <- "경상남도 창원시 마산합포구 중앙동3가"
address_list[662] <- "경상남도 창원시 마산합포구 창포동1가"
address_list[663] <- "경상남도 창원시 마산합포구 창포동2가"
address_list[664] <- "경상남도 창원시 마산합포구 창포동3가"
address_list[665] <- "경상남도 창원시 마산합포구 청계동"
address_list[676] <- "경상남도 창원시 마산회원구 석전동"
address_list[682] <- "경상남도 창원시 성산구 가음정동"
address_list[716] <- "경상남도 창원시 성산구 적현동"
address_list[722] <- "경상남도 창원시 의창구 내리동"
address_list[723] <- "경상남도 창원시 의창구 대산면"
address_list[747] <- "경상남도 창원시 진해구 가주동"
address_list[760] <- "경상남도 창원시 진해구 도만동"
address_list[761] <- "경상남도 창원시 진해구 도청동"
address_list[763] <- "경상남도 창원시 진해구 두동"
address_list[769] <- "경상남도 창원시 진해구 비봉동"
address_list[772] <- "경상남도 창원시 진해구 성내동"
address_list[774] <- "경상남도 창원시 진해구 속천동"
address_list[789] <- "경상남도 창원시 진해구 익선동"
address_list[791] <- "경상남도 창원시 진해구 인의동"
address_list[792] <- "경상남도 창원시 진해구 자은동"
address_list[798] <- "경상남도 창원시 진해구 중평동"
address_list[800] <- "경상남도 창원시 진해구 청안동"
address_list[814] <- "경상남도 김해시 장유동"
address_list
